#!/usr/bin/env python3
"""Send one clearly marked Cadova PDF test to the explicitly authorized address.

Requires SUPABASE_ACCESS_TOKEN and SUPABASE_PROJECT_REF in the environment.
Run only after deploying the quote-document schema and worker. A temporary,
confirmed Auth account signs in normally and exercises the same user RPCs,
private Storage upload and initial-delivery endpoint as the application.
Credentials remain in memory. The helper never queries Resend's read API.
Only resources generated by this invocation are eligible for cleanup.
"""

import argparse
import base64
from datetime import datetime, timezone
import hashlib
import hmac
import json
import os
from pathlib import Path
import re
import secrets
import sys
import time
import urllib.error
import urllib.request
import uuid
from zoneinfo import ZoneInfo


EMAIL_PATTERN = re.compile(r"^[^\s@<>]+@[^\s@<>]+\.[^\s@<>]+$")
UUID_PATTERN = re.compile(r"^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$")
MAX_RESPONSE_BYTES = 2 * 1024 * 1024


class VerificationError(Exception):
    """Messages are fixed, safe classifications, never response bodies."""


def checked_uuid(value, stage):
    if not isinstance(value, str) or not UUID_PATTERN.fullmatch(value):
        raise VerificationError(f"{stage}: invalid resource identifier")
    return value


def sql_literal(value):
    return "'" + value.replace("'", "''") + "'"


def request(url, headers, stage, method="GET", body=None, raw=None):
    """Return status and bounded bytes without exposing URLs or HTTP bodies."""
    payload = json.dumps(body).encode() if body is not None else raw
    request_headers = dict(headers)
    if body is not None:
        request_headers["Content-Type"] = "application/json"
    operation = urllib.request.Request(
        url, data=payload, headers=request_headers, method=method,
    )
    try:
        with urllib.request.urlopen(operation, timeout=60) as response:
            data = response.read(MAX_RESPONSE_BYTES + 1)
            status = response.status
    except urllib.error.HTTPError as error:
        status = error.code
        data = error.read(MAX_RESPONSE_BYTES + 1)
    except (urllib.error.URLError, TimeoutError, OSError):
        raise VerificationError(f"{stage}: request failed") from None
    if len(data) > MAX_RESPONSE_BYTES:
        raise VerificationError(f"{stage}: response exceeds the verification limit")
    return status, data


def request_json(url, headers, stage, method="GET", body=None, expected=(200, 201, 204)):
    status, data = request(url, headers, stage, method, body)
    if status not in expected:
        raise VerificationError(f"{stage}: HTTP {status}")
    if not data:
        return None
    try:
        return json.loads(data)
    except (ValueError, UnicodeDecodeError):
        raise VerificationError(f"{stage}: invalid JSON response") from None


class DocumentVerification:
    def __init__(self, recipient):
        if not isinstance(recipient, str) or len(recipient) > 254 or not EMAIL_PATTERN.fullmatch(recipient.strip()) or any(ord(char) < 32 for char in recipient):
            raise VerificationError("Provide the explicitly authorized test recipient with --send-to.")
        self.recipient = recipient.strip().lower()
        access_token = os.environ.get("SUPABASE_ACCESS_TOKEN", "")
        ref = os.environ.get("SUPABASE_PROJECT_REF", "")
        if not access_token or not re.fullmatch(r"[a-z0-9]{20}", ref):
            raise VerificationError("Set SUPABASE_ACCESS_TOKEN and SUPABASE_PROJECT_REF securely.")
        self.ref = ref
        self.management = f"https://api.supabase.com/v1/projects/{ref}"
        self.management_headers = {"Authorization": f"Bearer {access_token}"}
        self.url = f"https://{ref}.supabase.co"
        self.endpoint = f"{self.url}/functions/v1/send-quote-document"
        self.run_id = str(uuid.uuid4())
        self.email = f"cadova-e2e-{self.run_id}@example.invalid"
        self.company_name = f"TEST CADOVA PDF {self.run_id}"
        self.password = "CvT9!" + secrets.token_urlsafe(32)
        self.user_id = None
        self.company_id = None
        self.quote_ids = [str(uuid.uuid4()), str(uuid.uuid4())]
        self.document_id = str(uuid.uuid4())
        self.paths = []
        self.server_headers = None
        self.user_headers = None
        self.anon_headers = None
        self.baseline = None
        self.checks = {}
        self.started_at = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

    def query(self, sql, stage):
        result = request_json(
            f"{self.management}/database/query", self.management_headers,
            stage, "POST", {"query": sql},
        )
        if not isinstance(result, list):
            raise VerificationError(f"{stage}: invalid database response")
        return result

    def rpc(self, name, body, stage):
        return request_json(
            f"{self.url}/rest/v1/rpc/{name}", self.user_headers, stage, "POST", body,
        )

    def snapshot(self):
        # Counts never expose account addresses, credentials or business data.
        result = self.query("""
          select (select count(*) from auth.users) as auth_users,
            (select count(*) from public.platform_admins) as administrators,
            (select count(*) from public.companies) as companies,
            (select count(*) from public.company_members) as memberships,
            (select count(*) from public.clients) as clients,
            (select count(*) from public.quotes) as quotes,
            (select count(*) from public.quote_documents) as documents,
            (select count(*) from public.quote_initial_send_jobs) as initial_jobs,
            (select count(*) from public.quote_initial_send_payloads) as initial_payloads,
            (select count(*) from public.quote_events) as events,
            (select count(*) from public.notifications) as notifications,
            (select count(*) from public.quote_followup_automations) as automations,
            (select count(*) from public.quote_followup_jobs) as followup_jobs,
            (select count(*) from storage.objects where bucket_id='quote-documents') as stored_pdfs;
        """, "snapshot_counts")
        if len(result) != 1:
            raise VerificationError("snapshot_counts: invalid database response")
        return result[0]

    def inspect(self):
        project = request_json(self.management, self.management_headers, "inspect_project")
        if not isinstance(project, dict) or project.get("status") != "ACTIVE_HEALTHY":
            raise VerificationError("The selected Supabase project is not active and healthy.")
        readiness = self.query("""
          select to_regclass('public.quote_documents') is not null as documents,
            to_regclass('public.quote_initial_send_jobs') is not null as initial_jobs,
            to_regprocedure('public.save_imported_quote(uuid,uuid,uuid,jsonb,text,bigint,text,boolean,date,date,jsonb)') is not null as imports;
        """, "inspect_schema")
        if len(readiness) != 1 or not all(readiness[0].values()):
            raise VerificationError("Deploy the quote-document schema and worker before this test.")
        keys = request_json(
            f"{self.management}/api-keys", self.management_headers, "load_project_keys",
        )
        if not isinstance(keys, list):
            raise VerificationError("The project did not provide its server and public API keys.")
        service_key = next((item.get("api_key") for item in keys if item.get("name") == "service_role"), None)
        anon_key = next((item.get("api_key") for item in keys if item.get("name") == "anon"), None)
        if not service_key or not anon_key:
            raise VerificationError("The project did not provide its server and public API keys.")
        self.server_headers = {"apikey": service_key, "Authorization": f"Bearer {service_key}"}
        self.anon_headers = {"apikey": anon_key, "Authorization": f"Bearer {anon_key}"}
        self.baseline = self.snapshot()

    def create_test_account(self):
        created = request_json(
            f"{self.url}/auth/v1/admin/users", self.server_headers,
            "create_test_account", "POST", {
                "email": self.email, "password": self.password, "email_confirm": True,
                "user_metadata": {"cadova_e2e": self.run_id},
            },
        )
        if not isinstance(created, dict):
            raise VerificationError("create_test_account: invalid Auth response")
        self.user_id = checked_uuid(created.get("id"), "create_test_account")
        session = request_json(
            f"{self.url}/auth/v1/token?grant_type=password", self.anon_headers,
            "sign_in_test_account", "POST", {"email": self.email, "password": self.password},
        )
        token = session.get("access_token") if isinstance(session, dict) else None
        if not isinstance(token, str) or not token:
            raise VerificationError("sign_in_test_account: Auth did not return a session")
        if session.get("user", {}).get("id") != self.user_id:
            raise VerificationError("sign_in_test_account: unexpected authenticated identity")
        self.user_headers = {"apikey": self.anon_headers["apikey"], "Authorization": f"Bearer {token}"}
        if self.rpc("is_platform_admin", {}, "check_test_account_role") is not False:
            raise VerificationError("The temporary test account must not be an administrator.")
        self.checks["normal_auth_sign_in"] = True

    def prepare_quote(self):
        self.company_id = checked_uuid(self.rpc(
            "create_company_with_owner", {"company_name": self.company_name}, "create_test_company",
        ), "create_test_company")
        self.rpc("set_company_email_settings", {
            "p_company_id": self.company_id, "p_reply_to": self.recipient,
            "p_automation_paused": True,
        }, "set_test_reply_address")
        pdf = (Path(__file__).resolve().parents[1] / "tests/fixtures/document-text.pdf").read_bytes()
        if not pdf.startswith(b"%PDF-") or not 5 <= len(pdf) <= 10 * 1024 * 1024:
            raise VerificationError("The local test fixture must be a PDF of at most 10 MiB.")
        path = f"{self.company_id}/{self.user_id}/{self.document_id}.pdf"
        self.paths.append(path)  # Record before upload, including lost-response recovery.
        status, _ = request(
            f"{self.url}/storage/v1/object/quote-documents/{path}",
            {**self.user_headers, "Content-Type": "application/pdf", "x-upsert": "false", "Cache-Control": "max-age=0"},
            "upload_test_pdf", "POST", raw=pdf,
        )
        if status not in (200, 201):
            raise VerificationError(f"upload_test_pdf: HTTP {status}")
        document = {
            "id": self.document_id, "storage_path": path,
            "file_name": "test-cadova-devis.pdf", "size_bytes": len(pdf),
        }
        quote = self.rpc("save_imported_quote", {
            "p_quote_id": self.quote_ids[0], "p_company_id": self.company_id,
            "p_client_id": None, "p_new_client": {"name": "Destinataire du test Cadova", "email": self.recipient},
            "p_reference": f"TEST-CADOVA-PDF-{self.run_id[:8]}", "p_amount_cents": 120000,
            "p_notes": "Test technique isolé. Ce devis ne correspond à aucune prestation.",
            "p_already_sent": False, "p_sent_at": None, "p_expires_at": None,
            "p_document": document,
        }, "save_test_draft")
        if not isinstance(quote, dict) or quote.get("id") != self.quote_ids[0] or quote.get("status") != "draft":
            raise VerificationError("save_test_draft: the import did not create the expected draft")
        self.client_id = checked_uuid(quote.get("client_id"), "save_test_draft")
        status, downloaded = request(
            f"{self.url}/storage/v1/object/quote-documents/{path}", self.user_headers,
            "download_private_pdf",
        )
        if status != 200 or downloaded != pdf:
            raise VerificationError("The signed-in owner could not read the unchanged original PDF.")
        status, _ = request(
            f"{self.url}/storage/v1/object/quote-documents/{path}", self.anon_headers,
            "check_anonymous_pdf_denial",
        )
        if status not in (400, 401, 403, 404):
            raise VerificationError("Anonymous access to the private PDF was not denied.")
        self.checks["private_pdf_upload_and_download"] = True
        self.checks["anonymous_pdf_denied"] = True
        return pdf

    def delivery_details(self):
        quote_id = sql_literal(self.quote_ids[0]) + "::uuid"
        result = self.query("""
          select q.status as quote_status,q.sent_at is not null as quote_has_sent_date,
            j.id as job_id,j.status as job_status,j.attempts,j.provider_message_id,
            (select count(*) from public.quote_initial_send_jobs where quote_id=q.id) as jobs,
            (select count(*) from public.quote_events e where e.quote_id=q.id and e.event_type='sent' and e.initial_send_job_id=j.id) as sent_events,
            (select count(*) from public.notifications n where n.related_quote_id=q.id and n.type='quote_sent' and n.initial_send_job_id=j.id) as sent_notifications,
            (select count(*) from public.quote_followup_automations a where a.quote_id=q.id) as automations,
            (select count(*) from public.quote_followup_jobs f where f.quote_id=q.id) as followup_jobs
          from public.quotes q left join public.quote_initial_send_jobs j on j.quote_id=q.id
          where q.id=""" + quote_id + ";", "inspect_initial_delivery")
        if len(result) != 1:
            raise VerificationError("inspect_initial_delivery: expected one quote and one job")
        return result[0]

    def send_test(self, pdf):
        body = {
            "action": "send", "quoteId": self.quote_ids[0], "recipientEmail": self.recipient,
            "subject": f"Test Cadova : envoi du PDF {self.run_id[:8]}",
            "message": "Bonjour,\n\nCeci est le test d’envoi du devis PDF demandé pour Cadova. La pièce jointe est un exemple technique : aucune prestation ni aucun paiement n’est demandé.\n\nCe test vérifie l’import, l’envoi initial et son historique. Aucune relance automatique ne sera activée.",
            "retry": False,
        }
        # Exactly one initial invocation. A transport failure is reconciled by
        # read-only SQL, never by automatically posting the send request again.
        transport_error = None
        try:
            response = request_json(
                self.endpoint, self.user_headers, "send_one_test_email", "POST", body,
            )
        except VerificationError as error:
            transport_error = error
            response = None
        details = None
        for attempt in range(16):
            details = self.delivery_details()
            if details.get("job_status") in ("sent", "failed", "delivery_unknown"):
                break
            if attempt < 15:
                time.sleep(2)
        if not details or details.get("job_status") != "sent":
            if transport_error:
                raise transport_error
            raise VerificationError("The provider did not confirm the initial test delivery; inspect the temporary quote before retrying.")
        expected = {
            "quote_status": "sent", "quote_has_sent_date": True, "job_status": "sent",
            "attempts": 1, "jobs": 1, "sent_events": 1, "sent_notifications": 1,
            "automations": 0, "followup_jobs": 0,
        }
        if any(details.get(key) != value for key, value in expected.items()) or not details.get("provider_message_id"):
            raise VerificationError("The confirmed delivery did not produce one send, one event and one notification.")
        job_id = checked_uuid(details.get("job_id"), "inspect_initial_delivery")
        if response is not None and (not isinstance(response, dict) or response.get("state") != "sent" or response.get("job", {}).get("id") != job_id):
            raise VerificationError("The initial delivery response did not match its saved result.")
        payload = self.query("""
          select attachment_sha256,payload->>'to' as recipient,
            payload->'attachments'->0->>'content' as attachment
          from public.quote_initial_send_payloads where job_id=""" + sql_literal(job_id) + "::uuid;", "verify_original_attachment")
        if len(payload) != 1 or payload[0].get("attachment_sha256") != hashlib.sha256(pdf).hexdigest() or payload[0].get("recipient") != self.recipient or payload[0].get("attachment") != base64.b64encode(pdf).decode():
            raise VerificationError("The frozen provider payload did not contain the original PDF and confirmed recipient.")
        status, _ = request(
            f"{self.url}/rest/v1/quote_initial_send_payloads?select=job_id&job_id=eq.{job_id}",
            self.user_headers, "check_private_payload_denial",
        )
        if status not in (401, 403):
            raise VerificationError("The browser role was not denied access to private provider payloads.")
        self.checks["provider_accepted_original_pdf"] = True
        self.checks["single_sent_event_and_notification"] = True
        self.checks["private_payload_denied"] = True
        self.checks["followups_remain_opt_in"] = True
        repeated = request_json(
            self.endpoint, self.user_headers, "verify_repeated_request_is_idempotent", "POST",
            {**body, "retry": True},
        )
        after = self.delivery_details()
        if not isinstance(repeated, dict) or repeated.get("state") != "sent" or repeated.get("job", {}).get("id") != job_id or after != details:
            raise VerificationError("The repeated request did not retain the same accepted job without another attempt.")
        self.checks["repeated_request_did_not_send_again"] = True

    def check_already_sent(self):
        sent_date = datetime.now(ZoneInfo("Europe/Paris")).date().isoformat()
        result = self.rpc("save_imported_quote", {
            "p_quote_id": self.quote_ids[1], "p_company_id": self.company_id,
            "p_client_id": self.client_id, "p_new_client": None,
            "p_reference": f"TEST-CADOVA-DEJA-ENVOYE-{self.run_id[:8]}", "p_amount_cents": 120000,
            "p_notes": "Test de l’option Déjà envoyé. Aucun email à envoyer.",
            "p_already_sent": True, "p_sent_at": sent_date, "p_expires_at": None, "p_document": None,
        }, "save_already_sent_quote")
        if not isinstance(result, dict) or result.get("status") != "sent" or result.get("sent_at") != sent_date:
            raise VerificationError("The already-sent import did not preserve the confirmed date.")
        status, data = request(self.endpoint, self.user_headers, "check_already_sent_send_denial", "POST", {
            "action": "send", "quoteId": self.quote_ids[1], "recipientEmail": self.recipient,
            "subject": "Test Cadova : cet envoi doit être refusé",
            "message": "Ce devis est déjà envoyé. Aucun nouvel email ne doit être envoyé.",
        })
        try:
            response = json.loads(data)
        except (ValueError, UnicodeDecodeError):
            response = None
        if status != 409 or not isinstance(response, dict) or response.get("errorCode") != "already_sent":
            raise VerificationError("The already-sent quote was not rejected before creating a send job.")
        audit = self.query("""
          select (select count(*) from public.quote_initial_send_jobs where quote_id=""" + sql_literal(self.quote_ids[1]) + """::uuid) as jobs,
            (select count(*) from public.quote_events where quote_id=""" + sql_literal(self.quote_ids[1]) + """::uuid and event_type='sent') as sent_events;
        """, "inspect_already_sent_quote")
        if len(audit) != 1 or audit[0] != {"jobs": 0, "sent_events": 1}:
            raise VerificationError("The already-sent quote must create one history event and no send job.")
        self.checks["already_sent_saved_without_email"] = True

    def recover_created_resources(self):
        # A create response may have been lost. Unique generated identity and
        # company name permit recovery without touching a pre-existing account.
        rows = self.query("select id from auth.users where email=" + sql_literal(self.email) + ";", "recover_test_identity")
        if len(rows) > 1:
            raise VerificationError("cleanup: unexpected duplicate test identity")
        if rows:
            recovered = checked_uuid(rows[0].get("id"), "recover_test_identity")
            if self.user_id is not None and self.user_id != recovered:
                raise VerificationError("cleanup: test identity changed unexpectedly")
            self.user_id = recovered
        if self.user_id:
            companies = self.query("""
              select c.id from public.companies c join public.company_members m on m.company_id=c.id
              where c.name=""" + sql_literal(self.company_name) + " and m.user_id=" + sql_literal(self.user_id) + "::uuid;", "recover_test_company")
            if len(companies) > 1:
                raise VerificationError("cleanup: unexpected duplicate test company")
            if companies:
                recovered = checked_uuid(companies[0].get("id"), "recover_test_company")
                if self.company_id is not None and self.company_id != recovered:
                    raise VerificationError("cleanup: test company changed unexpectedly")
                self.company_id = recovered
            if self.company_id and not self.paths:
                self.paths = [f"{self.company_id}/{self.user_id}/{self.document_id}.pdf"]

    def cleanup(self):
        if self.server_headers is None:
            return {"completed": True, "created_resources": False}
        self.recover_created_resources()
        if self.user_id:
            identity = self.query("""
              select email=""" + sql_literal(self.email) + """ as generated_identity,
                not exists(select 1 from public.platform_admins p where p.user_id=u.id) as not_admin
              from auth.users u where id=""" + sql_literal(self.user_id) + "::uuid;", "protect_existing_accounts")
            if identity and (len(identity) != 1 or not all(identity[0].values())):
                raise VerificationError("cleanup refused: identity is not the generated non-admin account")
        if self.company_id:
            company = sql_literal(self.company_id) + "::uuid"
            ownership = self.query("""
              select c.name=""" + sql_literal(self.company_name) + """ as generated_company,
                not exists(select 1 from public.company_members m where m.company_id=c.id and m.user_id<>""" + sql_literal(self.user_id) + """::uuid) as isolated_membership,
                not exists(select 1 from public.quotes q where q.company_id=c.id and q.id not in (""" + ",".join(sql_literal(item) + "::uuid" for item in self.quote_ids) + """)) as isolated_quotes,
                not exists(select 1 from public.quote_initial_send_jobs j where j.company_id=c.id and j.status in ('processing','delivery_unknown')) as no_uncertain_send
              from public.companies c where c.id=""" + company + ";", "protect_existing_companies")
            if ownership and (len(ownership) != 1 or not all(ownership[0].values())):
                raise VerificationError("cleanup incomplete: the temporary company is no longer isolated or an initial send remains uncertain")
            # No broad deletes: two known quote IDs, then the one known company.
            if ownership:
                pending = self.query("select id from public.quote_initial_send_jobs where company_id=" + company + " and status='preparing';", "inspect_unsent_test_jobs")
                for job in pending:
                    if self.user_headers is None:
                        raise VerificationError("cleanup incomplete: the temporary unsent job requires its user's session")
                    self.rpc("cancel_quote_initial_send", {"p_job_id": checked_uuid(job.get("id"), "inspect_unsent_test_jobs")}, "cancel_unsent_test_job")
                ids = ",".join(self.quote_ids)
                request_json(
                    f"{self.url}/rest/v1/quotes?company_id=eq.{self.company_id}&id=in.({ids})",
                    self.server_headers, "delete_test_quotes", "DELETE",
                )
                request_json(
                    f"{self.url}/rest/v1/companies?id=eq.{self.company_id}",
                    self.server_headers, "delete_test_company", "DELETE",
                )
            self.cleanup_documents()
        if self.user_id:
            request_json(
                f"{self.url}/auth/v1/admin/users/{self.user_id}", self.server_headers,
                "delete_test_account", "DELETE",
            )
        leftovers = self.query("""
          select exists(select 1 from auth.users where email=""" + sql_literal(self.email) + """ ) as account,
            exists(select 1 from public.companies where name=""" + sql_literal(self.company_name) + " ) as company;", "verify_test_cleanup")
        if len(leftovers) != 1 or any(leftovers[0].values()):
            raise VerificationError("cleanup incomplete: generated test resources remain")
        after = self.snapshot()
        differences = {
            key: after[key] - self.baseline[key]
            for key in self.baseline if after[key] != self.baseline[key]
        } if self.baseline is not None else {}
        return {"completed": True, "created_resources": self.user_id is not None, "count_differences": differences}

    def cleanup_documents(self):
        if not self.paths:
            return
        own_paths = ",".join(sql_literal(path) for path in self.paths)
        attached = self.query("select count(*) as count from public.quote_documents where storage_path in (" + own_paths + ");", "check_test_documents_detached")
        if len(attached) != 1 or attached[0].get("count") != 0:
            raise VerificationError("cleanup incomplete: a generated PDF is still attached")
        candidates = self.query("""
          select
            (select count(*) from public.quote_document_cleanup c where c.storage_path not in (""" + own_paths + """) and
              ((c.status='queued' and c.next_attempt_at<=clock_timestamp()) or (c.status='processing' and c.lease_until<=clock_timestamp())))
            +(select count(*) from storage.objects o where o.bucket_id='quote-documents' and o.name not in (""" + own_paths + """)
              and o.created_at<clock_timestamp()-interval '24 hours'
              and not exists(select 1 from public.quote_documents d where d.storage_path=o.name)
              and not exists(select 1 from public.quote_document_cleanup c where c.storage_path=o.name)) as foreign_candidates;
        """, "inspect_isolated_cleanup")
        used_worker = False
        if len(candidates) == 1 and candidates[0].get("foreign_candidates") == 0:
            credentials = self.query("select decrypted_secret from vault.decrypted_secrets where name='cadova_quote_followup_scheduler_secret';", "load_cleanup_credential")
            if len(credentials) != 1 or not isinstance(credentials[0].get("decrypted_secret"), str):
                raise VerificationError("cleanup incomplete: scheduler credential unavailable")
            credential = credentials[0]["decrypted_secret"]
            issued = str(int(time.time()))
            nonce = str(uuid.uuid4())
            digest = hmac.new(credential.encode(), f"quote-documents-cleanup:{issued}:{nonce}".encode(), hashlib.sha256).hexdigest()
            proof = f"cadova-documents-v1:{issued}:{nonce}:{digest}"
            result = request_json(
                self.endpoint, {"Authorization": f"Bearer {proof}"}, "run_document_cleanup",
                "POST", {"action": "cleanup"},
            )
            if not isinstance(result, dict) or result.get("pending") != 0:
                raise VerificationError("cleanup incomplete: the private worker reported pending PDF removals")
            used_worker = True
        # An upload can succeed before the atomic attachment RPC fails; it has
        # no deletion tombstone yet. Remove only these exact, unbound test paths.
        # With foreign cleanup candidates, scoped Storage deletion also avoids
        # invoking the global batch against another tenant's pending entries.
        remaining = self.query("select name from storage.objects where bucket_id='quote-documents' and name in (" + own_paths + ");", "inspect_remaining_test_pdfs")
        if remaining:
            request_json(
                f"{self.url}/storage/v1/object/quote-documents", self.server_headers,
                "remove_only_test_pdfs", "DELETE", {"prefixes": [row["name"] for row in remaining]},
            )
        # Tombstones can safely disappear only for this deleted company/user's
        # unique paths. The signed cleanup nonce remains until normal expiry.
        self.query("""
          delete from public.quote_document_cleanup c where c.storage_path in (""" + own_paths + """)
            and not exists(select 1 from storage.objects o where o.bucket_id='quote-documents' and o.name=c.storage_path)
            and not exists(select 1 from public.quote_documents d where d.storage_path=c.storage_path);
        """, "verify_physical_pdf_cleanup")
        counts = self.query("""
          select (select count(*) from storage.objects where bucket_id='quote-documents' and name in (""" + own_paths + """))
            +(select count(*) from public.quote_document_cleanup where storage_path in (""" + own_paths + """)) as remaining;
        """, "confirm_physical_pdf_cleanup")
        if len(counts) != 1 or counts[0].get("remaining") != 0:
            raise VerificationError("cleanup incomplete: a generated PDF or its queue row remains")
        self.checks["private_cleanup_worker_exercised"] = used_worker

    def run(self):
        report = {"status": "failed", "project_ref": self.ref, "started_at": self.started_at}
        failure = None
        try:
            self.inspect()
            self.create_test_account()
            pdf = self.prepare_quote()
            self.send_test(pdf)
            self.check_already_sent()
            report["status"] = "verified"
        except VerificationError as error:
            failure = str(error)
        except Exception:
            # Unexpected exceptions must never serialize response objects or keys.
            failure = "Unexpected verification failure; inspect the generated resources before retrying."
        finally:
            try:
                report["cleanup"] = self.cleanup()
            except VerificationError as error:
                report["cleanup"] = {"completed": False, "error": str(error)}
                report["recovery"] = {"test_user_id": self.user_id, "test_company_id": self.company_id, "test_quote_ids": self.quote_ids}
                failure = failure or "The test completed but isolated cleanup is incomplete."
            except Exception:
                report["cleanup"] = {"completed": False, "error": "Unexpected isolated cleanup failure."}
                report["recovery"] = {"test_user_id": self.user_id, "test_company_id": self.company_id, "test_quote_ids": self.quote_ids}
                failure = failure or "Isolated cleanup is incomplete."
        report["checks"] = self.checks
        if failure:
            report["status"] = "failed"
            report["error"] = failure
        report["completed_at"] = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")
        return report


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--send-to", required=True, metavar="AUTHORIZED_EMAIL",
        help="Explicitly authorize one real Test Cadova email to the previously confirmed recipient.",
    )
    args = parser.parse_args()
    try:
        result = DocumentVerification(args.send_to).run()
    except VerificationError as error:
        result = {"status": "failed", "error": str(error)}
    print(json.dumps(result, ensure_ascii=False))
    raise SystemExit(0 if result["status"] == "verified" else 1)
